# Author @patriciogv - 2015

import:
    - https://tangrams.github.io/blocks/global.yaml
    - https://tangrams.github.io/blocks/filter/height.yaml

sources:
    osm:
        type: TopoJSON
        url: https://vector.mapzen.com/osm/all/{z}/{x}/{y}.topojson?api_key=mapzen-ZHhT9en
        max_zoom: 16
        generate_label_centroids: true
    pdok:
        type: GeoJSON
        url: data/ovlicht.geojson
        max_zoom: 16      
cameras:
    cam:
        type: isometric
        # vanishing_point: [0, -500]

lights:
    dir:
        type: directional
        direction: [.1, .5, -1]
        diffuse: .0
        ambient: .0
    light2:
        visible: true
        type: point
        position: [0,0,-900]
        origin: world
        ambient: .5
        diffuse: 0.7
        specular: .1       

layers:
    water:
        data: { source: osm }
        draw:
            water:
                order: global.order
                color: '#353535'
    earth:
        data: { source: osm }
        draw:
            earth:
                order: global.order
                color: '#111'
    landuse:
        data: { source: osm }
        draw:
            landuse:
                order: global.order
                color: '#222'
    roads:
        data: { source: osm }
        filter: { not: { kind: [rail, ferry] } }
        draw:
            roads:
                order: global.order
                color: [0.988, 0.988, 0.988]
                width: [[7,0.0px], [10, .5px], [15, .75px], [17, 5m]]
        highway:
            filter: { kind: highway }
            draw:
                roads:
                    order: global.order
                    width: [[8,0px], [8,.25px], [11, 1.5px], [14, 2px], [16, 4px], [17, 10m]]
            link:
                filter: { is_link: yes } # on- and off-ramps, etc
                draw:
                    roads:
                        width: [[8,0px], [14, 3px], [16, 5px], [18, 10m]]
                tunnel-link:
                    filter: {is_tunnel: yes, $zoom: {min: 13} }
        tunnel:
            filter: {is_tunnel: yes }
            draw:
                roads:
                    order: global.order
    buildings:
        data: { source: osm }
        draw:
            buildings:
                order: global.order
                color: '#fff'
                extrude: true
styles:
    water:
        base: polygons
    earth:
        base: polygons
    landuse:
        base: polygons
    roads:
        base: lines
        lighting: false
    buildings:
        base: polygons
        mix: [filter-height]
